### ISSUE TITLE
Segmentation fault in proteus Python script

### ISSUE THREAD

**Issue by varunsh-xilinx** [Xilinx/inference-server#31]
**Describe the bug**
On occasion, I've seen an error message from Python after running `proteus build` in the container showing a 'Segmentation fault'. The build succeeds this error occurs as the Python script terminates apparently. The exit code in the shell is 139. Enabling [faulthandler](https://docs.python.org/3/library/faulthandler.html) doesn't show much more (see screenshots below).

**To Reproduce**
It's inconsistent to reproduce but I started seeing it when running `proteus build` in recent commits.

**Expected behavior**
No error message

**Screenshots**

``` console
======================
Built Debug version
======================
Segmentation fault
proteus-dev:proteus$ echo $?
139
```

After enabling `faulthandler`:
``` console
======================
Built Debug version
======================
Fatal Python error: Segmentation fault

Current thread 0x00007f15809e3180 (most recent call first):
Segmentation fault
```

**OS/Versions:**
In the Docker container

**Comment by varunsh-xilinx** [comment]
Happened to catch it in GDB once:
```console
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x000000000059ccb4 in ?? ()
(gdb) where
#0  0x000000000059ccb4 in ?? ()
#1  0x000000000056803e in ?? ()
#2  0x00000000005a3957 in ?? ()
#3  0x00000000006317e9 in ?? ()
#4  0x000000000063184a in PyGC_Collect ()
#5  0x0000000000638489 in Py_FinalizeEx ()
#6  0x00000000006394f5 in Py_Main ()
#7  0x00000000004b0e50 in main ()
```
